select TO_CHAR(SNAP_TIME, 'YYYYMMDDHH24') SNAP_TIME ,
       SUM(EXECUTIONS)  EXECS
from  STATS$SQL_SUMMARY,STATS$SNAPSHOT
where STATS$SQL_SUMMARY.SNAP_ID=STATS$SNAPSHOT.SNAP_ID 
and   sql_id='c5zncy79xadn0'
group by TO_CHAR(SNAP_TIME, 'YYYYMMDDHH24')
order by 1  asc
